INSERT INTO Varekategori (id, kategorinavn, parent_id) VALUES
                                                           (1, 'Frukt og grønt', NULL),
                                                           (2, 'Bær', 1),
                                                           (3, 'Frukt', 1),
                                                           (4, 'Grønnsaker', 1),

                                                           (5, 'Kjøtt og fisk', NULL),
                                                           (6, 'Kjøtt', 5),
                                                           (7, 'Kylling', 5),
                                                           (8, 'Fisk', 5),
                                                           (9, 'Ferdig kjøtt og fisk', 5),

                                                           (10, 'Meieri og egg', NULL),
                                                           (11, 'Melk', 10),
                                                           (12, 'Ost', 10),
                                                           (13, 'Yoghurt', 10),
                                                           (14, 'Smør og margarin', 10),
                                                           (15, 'Egg', 10),

                                                           (16, 'Brød og frokost', NULL),
                                                           (17, 'Brød', 16),
                                                           (18, 'Knekkebrød', 16),
                                                           (19, 'Frokostblanding', 16),
                                                           (20, 'Pålegg', 16),
                                                           (21, 'Bakevarer', 16),

                                                           (22, 'Tørrvarer og middag', NULL),
                                                           (23, 'Pasta', 22),
                                                           (24, 'Ris', 22),
                                                           (25, 'Nudler', 22),
                                                           (26, 'Sauser', 22),
                                                           (27, 'Hermetikk', 22),
                                                           (28, 'Supper', 22),
                                                           (29, 'Baking', 22),

                                                           (30, 'Frossenmat', NULL),
                                                           (31, 'Frosne grønnsaker', 30),
                                                           (32, 'Frossen pizza', 30),
                                                           (33, 'Ferdigretter (frossen)', 30),

                                                           (34, 'Ferdigmat', NULL),
                                                           (35, 'Ferdigretter', 34),
                                                           (36, 'Salater', 34),
                                                           (37, 'På farten', 34),

                                                           (38, 'Snacks og godteri', NULL),
                                                           (39, 'Sjokolade', 38),
                                                           (40, 'Godteri', 38),
                                                           (41, 'Chips', 38),
                                                           (42, 'Kjeks', 38),
                                                           (43, 'Nøtter', 38),

                                                           (44, 'Drikke', NULL),
                                                           (45, 'Brus', 44),
                                                           (46, 'Juice', 44),
                                                           (47, 'Kaffe', 44),
                                                           (48, 'Te', 44),
                                                           (49, 'Energidrikk', 44),
                                                           (50, 'Øl', 44),

                                                           (51, 'Hjem og hygiene', NULL),
                                                           (52, 'Rengjøring', 51),
                                                           (53, 'Papirprodukter', 51),
                                                           (54, 'Personlig hygiene', 51),

                                                           (55, 'Dyremat', NULL),
                                                           (56, 'Hund', 55),
                                                           (57, 'Katt', 55),
                                                           (58, 'Beredskap og diverse', NULL);
