INSERT INTO Varetyper (id, varetype, kategori_id) VALUES
                                                      (1, 'Melk', 11),
                                                      (2, 'Gulost', 12),
                                                      (3, 'Hvitost', 12),
                                                      (4, 'Yoghurt', 13),
                                                      (5, 'Brød', 17),
                                                      (6, 'Knekkebrød', 18),
                                                      (7, 'Kjøttdeig', 6),
                                                      (8, 'Kyllingfilet', 7),
                                                      (9, 'Laks', 8),
                                                      (10, 'Egg', 15),
                                                      (11, 'Smør', 14),
                                                      (12, 'Spaghetti', 23),
                                                      (13, 'Penne', 23),
                                                      (14, 'Ris', 24),
                                                      (15, 'Pastasaus', 26),
                                                      (16, 'Hermetiske tomater', 27),
                                                      (17, 'Pizza', 32),
                                                      (18, 'Chips', 41),
                                                      (19, 'Sjokolade', 39),
                                                      (20, 'Cola', 45),
                                                      (21, 'Juice', 46),
                                                      (22, 'Kaffe', 47),
                                                      (23, 'Toalettpapir', 53),
                                                      (24, 'Tannkrem', 54),
                                                      (25, 'Hundemat', 56),
                                                      (26, 'Kattefôr', 57),
                                                      (27, 'Jordbær', 2),
                                                      (28, 'Blåbær', 2),
                                                      (29, 'Bringebær', 2),
                                                      (30, 'Boller', 21),
                                                      (31, 'Skinke', 20),
                                                      (32, 'Leverpostei', 20),
                                                      (33, 'Frosne grønnsaker', 31),
                                                      (34, 'Nudler', 25),
                                                      (35, 'Te', 48),
                                                      (36, 'Energidrikk', 49),
                                                      (37, 'Øl', 50),
                                                      (38, 'Nøtter', 43),
                                                      (39, 'Kjeks', 42),
                                                      (40, 'Godteri', 40),
                                                      (41, 'Beredskap', 58),
                                                      (42, 'Drivstoff', 58),
                                                      (43, 'Brensel', 58),
                                                      (44, 'Verktøy og utstyr', 58),
                                                      (45, 'Diverse beredskap', 58);
